name: Generate Snake

on:
  schedule: # run every 12 hours
    - cron: "0 */12 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: FonjiHill
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload the output
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

      - name: Push the output to the repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Generate snake animation'
          git push
